Generate random ads
htmlacademy-javascript/268075-keksobooking-24 pull request #3
Opened 2021-10-03 18:32 UTC by dmitry-buyan

2021-10-04 05:13 UTC, ademaro requested changes
В целом всё круто, молодец! Но давай чуть доделаем:
1. файлы моков давай поместим в папку, можем сделать два файла: mock/utils.js и mock/pins.js
2. пересмотри ошибки линтера и постарайся всё поправить
3. внести изменения из моих комментов

ПР пока оставляю открытым, жду ещё коммитов

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +const INTEGERS = {
перечисления оформляются не так, давай поправим

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +  const longitudeEnd = 139.80000;
вот это как раз в константы (или перечисление)

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +  eight: 8,
MIN_ROOMS, MAX_ROOMS — надо сделать такие константы или запаковать в перечисление: Rooms.MIN и Rooms.MAX

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +const INTEGERS = {
И вообще не очень понятно зачем ты это сделал? 0 (для первого индекса массива давай оставим в коде, не надо выносить в константы),

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +  types: ['palace', 'flat', 'house', 'bungalow', 'hotel',],
запятую лишнюю давай уберём

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +const getRandomIntegerFromRange = (a, b, digits = 0) => {
вместо a, b давай сразу поставим min, max, что бы линтер не ругался

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +const pad = (number) => number < INTEGERS.ten ? `${INTEGERS.zero}${number}` : number;
функции всегда с глаголом

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +  const maxPrice = 20000;
в константы

2021-10-04 05:13 UTC, ademaro commented on js/main.js
> +  const randomFeatures = shuffleArray(data.features).slice(randomFeaturesIndex);
сделай вспомогательную ф-цию `getRandomArrayFromAnother()`

2021-10-04 16:19 UTC, dmitry-buyan commented on js/main.js
> +const INTEGERS = {
Числовые значения перенес в константы (перечисления), чтобы избежать магических значений в коде

2021-10-04 17:36 UTC, dmitry-buyan commented on js/main.js
> +  const randomFeatures = shuffleArray(data.features).slice(randomFeaturesIndex);
не совсем понял. у меня же есть ф-я shuffleArray, которая принимает массив, копирует его, перемешивает и возвращает случайный массив

2021-10-05 23:02 UTC, ademaro commented on js/main.js
> +  const randomFeatures = shuffleArray(data.features).slice(randomFeaturesIndex);
я про эти две строчки, ты же их повторяешь из раза в раз, проще вынести в отдельную функцию

2021-10-05 23:02 UTC, ademaro commented
поправь ещё ошибки линтера

2021-10-06 10:22 UTC, ademaro commented on js/mock/pins.js
> +generatePins(PINS_COUNT);
генерацию пинов делать будем в main, тут просто экспортируем

2021-10-06 10:23 UTC, ademaro reviewed
Отлично, двигаем дальше

2021-10-06 10:23 UTC, merged